/* 
 * ProcessMaker API
 *
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine API that is designed to be used as a microservice to support enterprise cloud applications. The current Alpha 1.0 version supports most of the descriptive classes of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package pmio

type EventAttributes struct {

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	ProcessId string `json:"process_id,omitempty"`

	MessageId int32 `json:"message_id,omitempty"`

	Type_ string `json:"type,omitempty"`

	Definition string `json:"definition,omitempty"`

	Interrupting bool `json:"interrupting,omitempty"`

	Condition string `json:"condition,omitempty"`

	Time string `json:"time,omitempty"`

	Duration string `json:"duration,omitempty"`

	Cycle string `json:"cycle,omitempty"`

	AttachedToTaskId string `json:"attached_to_task_id,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
