/* 
 * ProcessMaker API
 *
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine API that is designed to be used as a microservice to support enterprise cloud applications. The current Alpha 1.0 version supports most of the descriptive classes of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package pmio

type TaskInstanceAttributes struct {

	TaskId string `json:"task_id,omitempty"`

	InstanceId string `json:"instance_id,omitempty"`

	GroupId string `json:"group_id,omitempty"`

	UserId string `json:"user_id,omitempty"`

	Status string `json:"status,omitempty"`

	Priority string `json:"priority,omitempty"`

	DelegateDate string `json:"delegate_date,omitempty"`

	StartDate string `json:"start_date,omitempty"`

	FinishDate string `json:"finish_date,omitempty"`

	TaskDueDate string `json:"task_due_date,omitempty"`

	RiskDate string `json:"risk_date,omitempty"`

	Duration int32 `json:"duration,omitempty"`

	InstanceOverduePercentage float64 `json:"instance_overdue_percentage,omitempty"`

	Data string `json:"data,omitempty"`

	Content string `json:"content,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
